[package]
name = "xlib-sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.8.2"
gl = "0.14.0"
glm = "0.2.3"
#legion = "0.3.1"
log = "0.4"

[dependencies.x11]
git = "https://github.com/malwrar/x11-rs"
branch = "backlog"
features = [ "xlib", "glx", "xcomposite", "xdamage" ]