[package]
name = "malicious"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8.3"
lazy_static = "1.4"
log = "0.4.0"
regex = "1.5"
zip = "0.5"
